name: 😱 Build with Qt 6

on:
  push:
    branches:
      - master
      - release-**
      - qt-for-python-qt5
    paths:
    - 'src/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - '.github/workflows/**'
    - '.ci/**'
    - '.docker/**'
  pull_request:
    branches:
      - master
      - release-**
    paths:
    - 'src/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - '.github/workflows/**'
    - '.ci/**'
    - '.docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup build dependencies
        run: |
          docker build -t qgis_build_deps -f .docker/qgis3-build-deps-qt-for-python.dockerfile .
      - name: Run build
        run: |
          docker run -v $(pwd):/usr/src/qgis qgis_build_deps /usr/src/qgis/.docker/docker-qgis-build-qt-for-python.sh

